import React, { useState } from "react";
import Head from "next/head";
import styles from "../../styles/Identities.module.css";
import { useStarknet, useStarknetCall } from "@starknet-react/core";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Button from "../../components/button";
import ClickableIcon from "../../components/clickableIcon";
import { GoVerified, GoUnverified } from "react-icons/go";
import { useStarknetIdContract } from "../../hooks/starknetId";
import { stringToFelt } from "../../utils/felt";
import { MutatingDots } from "react-loader-spinner";

export default function TokenId() {
  const router = useRouter();
  const { account } = useStarknet();
  const tokenIdAbbreviation =
    router.query.tokenId?.length > 5
      ? router.query.tokenId?.charAt(0) +
        router.query.tokenId?.charAt(1) +
        "..." +
        router.query.tokenId?.charAt(router.query.tokenId?.length - 2) +
        router.query.tokenId?.charAt(router.query.tokenId?.length - 1)
      : router.query.tokenId;

  //Contract calls
  const { contract } = useStarknetIdContract();
  const {
    data: isValidData,
    error: isValidError,
    loading,
  } = useStarknetCall({
    contract: contract,
    method: "is_valid",
    args: [
      [router.query.tokenId, 0],
      stringToFelt("discord"),
      process.env.NEXT_PUBLIC_VERIFIER,
    ],
  });
  const [isValidDiscord, setIsValidDiscord] = useState(false);

  function onDiscordClick() {
    sessionStorage.setItem("tokenId", router.query.tokenId);
    window.location.replace(
      "https://discord.com/oauth2/authorize?client_id=991638947451129886&redirect_uri=https%3A%2F%2Fstarknet.id%2Fdiscord&response_type=code&scope=identify"
    );
  }

  useEffect(() => {
    if (!account) {
      router.push("/home");
    }
  }, [account, router]);

  useEffect(() => {
    if (isValidError || !isValidData || Number(isValidData) === 0) {
      setIsValidDiscord(false);
    } else {
      setIsValidDiscord(true);
    }
  }, [isValidData, isValidError]);

  return (
    <div className="h-screen w-screen">
      <Head>
        <title>Starknet.id</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/starknet-logo.webp" />
      </Head>

      <div className={styles.container}>
        <h1 className="sm:text-5xl text-5xl my-2">
          Your identity : {tokenIdAbbreviation}
        </h1>

        <div className="flex">
          <div className="m-3">
            <ClickableIcon icon="steam" onClick={onDiscordClick} />
            <div className="flex justify-center items-center">
              <>
                <p className="mt-1 mr-1 font-bold">Unverified</p>
                <GoUnverified color="#FF5008" />
              </>
            </div>
          </div>
          <div className="m-3">
            <ClickableIcon icon="twitter" onClick={onDiscordClick} />
            <div className="flex justify-center items-center">
              <>
                <p className="mt-1 mr-1 font-bold">Unverified</p>
                <GoUnverified color="#FF5008" />
              </>
            </div>
          </div>
          <div className="m-3">
            <ClickableIcon icon="discord" onClick={onDiscordClick} />
            <div className="flex justify-center items-center">
              {loading ? (
                <MutatingDots
                  height="25"
                  width="25"
                  color="#ff5008"
                  secondaryColor="white"
                  ariaLabel="loading"
                />
              ) : isValidDiscord ? (
                <>
                  <p className="mt-1 mr-1 font-bold">Verified</p>
                  <GoVerified color="#FF5008" />
                </>
              ) : (
                <>
                  <p className="mt-1 mr-1 font-bold">Unverified</p>
                  <GoUnverified color="#FF5008" />
                </>
              )}
            </div>
          </div>
        </div>
        <Button onClick={() => router.push("/identities")}>
          Back to your identities
        </Button>
      </div>
    </div>
  );
}
