import React from "react";
import Head from "next/head";
import styles from "../../styles/Identities.module.css";
import { useStarknet } from "@starknet-react/core";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Button from "../../components/button";

import ClickableIcon from "../../components/clickableIcon";
import Image from "next/image";
import { GoVerified, GoUnverified } from "react-icons/go";

export default function TokenId() {
  const router = useRouter();
  const { account } = useStarknet();
  const tokenIdAbbreviation =
    router.query.tokenId.charAt(0) +
    router.query.tokenId.charAt(1) +
    "..." +
    router.query.tokenId.charAt(router.query.tokenId.length - 2) +
    router.query.tokenId.charAt(router.query.tokenId.length - 1);

  function onDiscordClick() {
    sessionStorage.setItem("tokenId", router.query.tokenId);
    window.location.replace(
      "https://discord.com/oauth2/authorize?client_id=991638947451129886&redirect_uri=https%3A%2F%2Fstarknet.id%2Fdiscord&response_type=code&scope=identify"
    );
  }

  function onTwitterClick() {
    sessionStorage.setItem("tokenId", router.query.tokenId);
    window.location.replace(
      "https://starknet.id/discord?code=qpC5DFAD2s4UANPu1mo9NqRopvgQiy"
    );
  }

  useEffect(() => {
    if (!account) {
      router.push("/home");
    }
  }, [account, router]);

  return (
    <div className="h-screen w-screen">
      <Head>
        <title>Starknet.id</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/starknet-logo.webp" />
      </Head>

      <div className={styles.container}>
        <h1 className="sm:text-5xl text-5xl my-2">
          Your identity : {tokenIdAbbreviation}
        </h1>

        <div className="flex">
          {/* <div>
                <Image
                  width={150}
                  height={150}
                  src="/../../public/defaultAvatar.jpeg"
                  alt="avatar"
                  className={styles.avatar}
                />
                <p className="mt-1">
                  <strong>Your avatar</strong>
                </p>
              </div> */}
          <div className="m-3">
            <ClickableIcon icon="twitter" onClick={onTwitterClick} />
            <div className="flex justify-center items-center">
              <p className="mt-1 mr-1 font-bold">Twitter Username</p>
              <GoVerified color="#FF5008" />
            </div>
          </div>
          <div className="m-3">
            <ClickableIcon icon="discord" onClick={onDiscordClick} />
            <div className="flex justify-center items-center">
              <p className="mt-1 mr-1 font-bold">Discord Username</p>
              <GoVerified color="#FF5008" />
            </div>
          </div>
        </div>
        <Button onClick={() => router.push("/identities")}>
          Back to your identities
        </Button>
      </div>
    </div>
  );
}
