import Head from "next/head";
import styles from "../styles/bets.module.css";
import { useConnectors, useStarknet } from "@starknet-react/core";
import Button from "../components/button";
import { useEffect } from "react";
import { useRouter } from "next/router";
import MintIdentity from "../components/mintOneIdentity";
import ClickableIcon from "../components/clickableIcon";

export default function Identities() {
  //React
  const router = useRouter();

  // Connection
  const { disconnect, connectors } = useConnectors();
  const connector = connectors[0];
  const { account } = useStarknet();

  useEffect(() => {
    if (!account) {
      router.push("/home");
    }
  }, [account, router]);

  return (
    <div className="h-screen w-screen">
      <Head>
        <title>Starkbet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/starknet-logo.webp" />
      </Head>
      <div className={styles.container}>
        <>
          <h1 className="sm:text-5xl text-5xl">Trending bets</h1>
          <div className={styles.containerGallery}>
            <div className="flex">
              <div className="m-3">
                <ClickableIcon
                  icon="temperature"
                  onClick={() => router.push("/bets/temperature")}
                />
              </div>
              <div className="m-3">
                <ClickableIcon
                  icon="ethereum"
                  onClick={() => router.push("/bets/ethereum")}
                />
              </div>
              <div className="m-3">
                <MintIdentity onClick={() => router.push("/create-bet")} />
              </div>
            </div>
          </div>
          <div>
            {connector?.available() ? (
              <Button
                key={connector.id()}
                onClick={() => disconnect(connector)}
              >
                Disconnect
              </Button>
            ) : null}
          </div>
        </>
      </div>
    </div>
  );
}
