import React, { useState } from "react";
import Head from "next/head";
import styles from "../../styles/bets.module.css";
import { useStarknet, useStarknetInvoke } from "@starknet-react/core";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Button from "../../components/button";
import BetInfos from "../../components/betInfos";
import { useStarkBetContract } from "../../hooks/starkBet";

export default function TokenId() {
  const [eventData, setEventData] = useState(undefined);
  const router = useRouter();
  const { account } = useStarknet();

  useEffect(() => {
    if (!account) {
      router.push("/home");
    }

    fetch(
      "http://starknet.events/api/v1/get_events?contract=0x00dd77122a448a5227eeec46ad7f0449256f15a958a71f37aa748d55760dbeaf"
    )
      .then((response) => response.json())
      .then((data) => setEventData(data));
  }, [account]);

  //Contract
  const { contract } = useStarkBetContract();

  return (
    <div className="h-screen w-screen">
      <Head>
        <title>Starknet.id</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/starknet-logo.webp" />
      </Head>

      <div className={styles.container}>
        <h1 className="sm:text-5xl text-5xl my-2">Ethereum bet</h1>

        <div className="flex">
          <BetInfos />
        </div>
        <Button onClick={() => router.push("/bets")}>Back to bets</Button>
      </div>
    </div>
  );
}
